# Generated by Django 6.0.5 on 2026-05-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diseases/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10, null=True)),
                ('category', models.CharField(blank=True, choices=[('FUNGAL', 'Fungal'), ('BACTERIAL', 'Bacterial'), ('VIRAL', 'Viral'), ('NUTRIENT_DEFICIENCY', 'Nutrient Deficiency'), ('PEST', 'Pest'), ('OTHER', 'Other')], max_length=30, null=True)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scientific_name', models.CharField(blank=True, max_length=150, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('CROP', 'Crop'), ('FRUIT', 'Fruit'), ('VEGETABLE', 'Vegetable'), ('HERB', 'Herb'), ('FLOWER', 'Flower'), ('TREE', 'Tree'), ('ORNAMENTAL', 'Ornamental'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('growing_season', models.CharField(blank=True, max_length=100, null=True)),
                ('growing_region', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'plants',
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('CHEMICAL', 'Chemical'), ('MECHANICAL', 'Mechanical'), ('ORGANIC', 'Organic')], max_length=20)),
            ],
            options={
                'db_table': 'treatments',
            },
        ),
        migrations.CreateModel(
            name='PlantDisease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_diseases', to='core.disease')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_diseases', to='core.plant')),
            ],
            options={
                'db_table': 'plant_diseases',
                'constraints': [models.UniqueConstraint(fields=('plant', 'disease'), name='unique_plant_disease')],
            },
        ),
        migrations.CreateModel(
            name='DiseaseTreatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_treatments', to='core.disease')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_treatments', to='core.treatment')),
            ],
            options={
                'db_table': 'disease_treatments',
                'constraints': [models.UniqueConstraint(fields=('disease', 'treatment'), name='unique_disease_treatment')],
            },
        ),
    ]
